name: CD Production-Lane
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch.
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Artifacts and Release
    runs-on: ubuntu-latest
    steps:
      - name: Decode android/neumodore_key.jks
        run: echo "${{ env.GITHUB_REPOSITORY }} ${{ secrets.KEYSTORE_JKS_PROD }}"
